version: 0.2

phases:
  pre_build:
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  baseDirectory: frontend/dist  # This should match the output directory of your build
  files:
    - '**/*'  # Include all files in the output directory


